const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const dir=path.resolve(__dirname,'..');
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(dir,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');try{res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');
let browser;try{
browser=await chromium.launch({headless:true,executablePath:process.env.TEST_CHROME});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/assets/auth.js*',r=>r.fulfill({contentType:'application/javascript',body:"document.body.classList.remove('rf-auth-pending');document.getElementById('authGate').style.display='none';"}));
await page.route('https://**',r=>r.abort());
await page.addInitScript(()=>{window.testSaved=null;window.AncalagonData={create:()=>({load:async()=>window.reloadFixture||({jobs:[],candidates:[],feedback:[],interviewOutcomes:[]}),schedule:(s,e,status)=>{window.testSaved=JSON.parse(JSON.stringify(s));status('saved')},flush:async s=>{window.testSaved=s},trackEvent:async()=>{},loadAdminAnalytics:async()=>{if(window.testAdmin)return{totals:{},users:[]};throw Error('not admin')}})};window.ancalagonAuth={session:{user:{id:'test'},access_token:'test-token'},workspace:{id:'test'}}});
await page.route('**/assets/data.js*',r=>r.fulfill({contentType:'application/javascript',body:''}));
await page.route('**/functions/v1/**',async route=>{const payload=route.request().postDataJSON();assert.ok(payload.evaluation_context);if(payload.analysis_type==='screening'){assert.ok(payload.evaluation_context.sources.some(s=>s.id.startsWith('feedback-')));await route.fulfill({json:{manager_score:9,jd_score:8.5,manager_reason:'Specific ownership example in candidate feedback supports manager priority.',jd_reason:'Qualification baseline unchanged.',summary:'Ownership evidence reviewed.',model:'test-model'}})}else await route.fulfill({json:{summary:'Pattern review',signals:[],resume_interview_gaps:[],recommended_weight_changes:[]}})});
await page.goto(`http://127.0.0.1:${server.address().port}/`);
await page.locator('#learnWelcome [data-goto="learn"]').click();
await page.locator('#page-learn.active').waitFor();
assert.equal(await page.locator('#page-learn .rf-learn-guides details').count(),5);
assert.equal(await page.evaluate(()=>window.testSaved?.candidates?.length||0),0);
await page.locator('#page-learn details').nth(1).locator('summary').click();
await page.locator('#page-learn [data-learn-page="candidates"]').click();
await page.locator('#page-jobs.active').waitFor();
await page.locator('#jobTitle').fill('Reliability test');await page.locator('#jobDescription').fill('Build and maintain Kubernetes infrastructure');await page.locator('#jobForm button[type=submit]').click();
await page.locator('#page-dashboard.active').waitFor();assert.equal(await page.evaluate(()=>window.testSaved.jobs[0].title),'Reliability test');
await page.locator('#addCandidateBtn').click();await page.locator('#candidateName').fill('Test Candidate');await page.locator('#candidateRole').fill('Engineer');await page.locator('#candidateScore').fill('8.5');await page.locator('#candidateSignal').fill('Infrastructure engineer');await page.locator('#candidateStrengths').fill('Built production Kubernetes clusters');await page.locator('#candidateForm button[type=submit]').click();
await page.locator('#page-detail.active').waitFor();assert.equal(await page.locator('#detailName').textContent(),'Test Candidate');assert.equal(await page.evaluate(()=>window.testSaved.candidates.length),1);await page.locator('.rf-nav [data-page="feedback"]').click();
await page.locator('#feedbackText').fill('Technically strong, ownership unclear');
await page.locator('#feedbackSubmitBtn').click();
await page.locator('.rf-feedback-interpretation').waitFor();
assert.equal(await page.evaluate(()=>window.testSaved.feedback[0].outcome),'Neutral / no signal');
assert.equal(await page.evaluate(()=>window.testSaved.candidates[0].managerScore),8.5);
await page.locator('.rf-feedback-interpretation summary').click();
await page.locator('[aria-label="Correct interpretation"]').fill('Clarify which production systems they owned personally.');
await page.locator('[data-correct-interpretation]').click();
assert.equal(await page.evaluate(()=>window.testSaved.feedback[0].interpretation.source),'recruiter');
await page.locator('#feedbackDetails summary').click();
await page.locator('#feedbackOutcome').selectOption('Positive / move forward',{force:true});
await page.locator('#feedbackText').fill('Strong ownership of production systems');
await page.locator('#feedbackSubmitBtn').click();
await page.locator('.rf-feedback-interpretation').nth(1).waitFor();
await page.waitForFunction(()=>window.testSaved.feedback.length===2&&window.testSaved.feedback.every(f=>f.interpretation));
await page.locator('.rf-nav [data-page="candidates"]').click();
await page.locator('[data-candidate-id]').first().click();
assert.match(await page.locator('#detailScreenEvidence').textContent(),/Candidate feedback/);
await page.locator('.rf-nav [data-page="insights"]').click();
await page.locator('#runHybridAnalysis').click();
await page.locator('#reevaluateCandidates').click();
await page.locator('[data-apply-reevaluation]').first().click();
assert.equal(await page.evaluate(()=>window.testSaved.candidates[0].managerScore),9);
await page.locator('.rf-nav [data-page="candidates"]').click();
await page.locator('[data-candidate-id]').first().click();
assert.match(await page.locator('#detailScreenEvidence').textContent(),/Evaluation matches current context/);
await page.locator('#workspaceNote').fill('Concrete testing examples; ask about automation ownership.');
await page.locator('#workspaceNoteForm button').click();
await page.waitForFunction(()=>window.testSaved.feedback.length===3&&window.testSaved.feedback[2].interpretation);
assert.equal(await page.evaluate(()=>window.testSaved.candidates[0].managerScore),9);
await page.locator('#submissionDraft').fill('Recruiter edited summary: testing evidence recorded; automation ownership needs confirmation.');
await page.locator('#saveSubmissionDraft').click();
assert.match(await page.evaluate(()=>window.testSaved.candidates[0].submissionDraft.text),/Recruiter edited/);
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);
await page.setViewportSize({width:1280,height:900});
await page.locator('#detailStage').selectOption('Hired',{force:true});
assert.equal(await page.evaluate(()=>window.testSaved.jobs[0].status),'closed');
const saved=await page.evaluate(()=>window.testSaved);
await page.addInitScript(state=>{window.reloadFixture=state},saved);
await page.reload();await page.locator('#page-job-picker.active').waitFor();
assert.match(await page.locator('#jobPickerGrid').textContent(),/Reliability test/);
assert.equal(await page.locator('#qualityLab').isVisible(),false);
await page.evaluate(()=>{window.testAdmin=true;document.getElementById('refreshAdminUsage').click()});
await page.locator('#adminUsageNav').click();
await page.locator('#qualityLab').waitFor({state:'visible'});
let qualityRequests=0;
await page.route('**/functions/v1/**',async route=>{
 const payload=route.request().postDataJSON();qualityRequests++;
 assert.ok(payload.evaluation_context.sources.every(s=>!s.text.includes('Test Candidate')));
 assert.equal(payload.evaluation_context.sources.some(s=>s.id==='feedback-followup'),qualityRequests%2===0);
 await route.fulfill({json:{manager_score:payload.candidate.current_manager_score,jd_score:7.5,confidence:'medium',summary:'Synthetic quality response',manager_reason:'Supplied evidence reviewed.',jd_reason:'No new qualification evidence.',model:'simulated-model'}});
});
await page.locator('#runQualitySuite').click();
await page.waitForFunction(()=>document.getElementById('qualityStatus').textContent.startsWith('Run complete'));
assert.equal(qualityRequests,8);
assert.equal(await page.locator('.rf-quality-case').count(),4);
await page.locator('.rf-quality-case').first().getByRole('button',{name:'Acceptable reasoning'}).click();
await page.locator('#quality-notes-impression-vs-interview').fill('Human review recorded');
const downloadPromise=page.waitForEvent('download');await page.locator('#exportQualityReport').click();const download=await downloadPromise;
const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
assert.equal(exported.results[0].humanReview,'acceptable');assert.equal(exported.results[0].reviewNotes,'Human review recorded');assert.ok(!JSON.stringify(exported).includes('test-token'));
await page.locator('#qualityBaseline').setInputFiles({name:'baseline.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
await page.waitForFunction(()=>document.getElementById('qualityComparison').textContent.includes('Same-suite comparison'));
assert.deepEqual(errors,[]);
console.log('Browser journey passed: create job and candidate, save feedback, reconcile score detail, hire and close job, reload workspace.');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
