const test=require('node:test'),assert=require('node:assert/strict');
const {create,normalize}=require('../assets/guidance.js');
function fixture(){let state={enabled:true,tips:{}},fail=false;return {get state(){return structuredClone(state);},set fail(value){fail=value;},load:async()=>structuredClone(state),save:async(action,tip)=>{if(fail)throw Error('Offline');if(action==='reset')state={enabled:true,tips:{}};else if(action==='enable'||action==='disable')state.enabled=action==='enable';else if(action==='dismiss'||!state.tips[tip])state.tips[tip]=action==='dismiss'?'dismissed':'completed';return structuredClone(state);}};}
test('guidance restores only known preferences',()=>{assert.deepEqual(normalize({enabled:false,tips:{assessment:'dismissed',feedback:'completed',approval:'bad',unknown:'dismissed'}}),{enabled:false,tips:{assessment:'dismissed',feedback:'completed'}});});
test('dismissals survive a new session; independent completed tips and visibility are preserved',async()=>{const api=fixture(),first=create(api);await first.load();await Promise.all([first.update('dismiss','assessment'),first.update('complete','feedback'),first.update('disable')]);const returning=create(api);await returning.load();assert.deepEqual(returning.view().state,{enabled:false,tips:{assessment:'dismissed',feedback:'completed'}});await returning.update('enable');assert.equal(returning.view().state.tips.assessment,'dismissed');await returning.update('reset');assert.deepEqual(returning.view().state,{enabled:true,tips:{}});});
test('a failed dismissal leaves the tip available and retry saves the exact preference',async()=>{const api=fixture(),session=create(api);await session.load();api.fail=true;assert.equal(await session.update('dismiss','approval'),false);assert.equal(session.view().state.tips.approval,undefined);assert.match(session.view().problem,/did not save/);api.fail=false;assert.equal(await session.retry(),true);assert.equal(session.view().state.tips.approval,'dismissed');assert.equal(session.view().problem,'');});
test('a late completion does not replace an explicit dismissal',async()=>{const api=fixture(),session=create(api);await session.load();await session.update('dismiss','feedback');await session.update('complete','feedback');assert.equal(session.view().state.tips.feedback,'dismissed');});
test('failed loading cannot overwrite saved preferences; disposal stops queued writes and late renders',async()=>{let saves=0,resolve,changes=0;const session=create({load:async()=>{throw Error('offline');},save:async()=>{saves++;}});await session.load();assert.equal(await session.update('reset'),false);assert.equal(saves,0);const late=create({load:()=>new Promise(r=>resolve=r),save:async()=>{saves++;},changed:()=>changes++});const pending=late.load();late.dispose();const before=changes;resolve({enabled:false,tips:{feedback:'completed'}});await pending;assert.equal(late.view().loaded,false);assert.equal(changes,before);assert.equal(await late.update('reset'),false);assert.equal(saves,0);});
test('queued writes capture one user session and stop on disposal',async()=>{let finish,saves=0;const session=create({load:async()=>null,save:()=>{saves++;return new Promise(r=>finish=r);}});await session.load();const first=session.update('dismiss','assessment');const second=session.update('dismiss','feedback');await Promise.resolve();session.dispose();finish({enabled:true,tips:{assessment:'dismissed'}});await Promise.all([first,second]);assert.equal(saves,1);assert.deepEqual(session.view().state.tips,{});});
