name: Activate criteria automation backend
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/core-backend.yml
    secrets: inherit
